---
title: "Conclusion"
author: "Chelsea Linares"
date: "2024-04-12"
output: github_document
---


This project has been incredible to work on, we researched, explored, analyzed, and interpreted our data, which is something that I will always treasure. After cleaning our data and determining which predictors we should keep, we created 6 different models to establish without a doubt the most efficient model at predicting whether client would be `Approved` or not for a credit card. We found it was Random Forest, which I was extremely proud of given the final roc_auc was very close to perfectly predicting all outcomes.

What did shock me and I think I will always keep this in the back of my mind is that banks prefer to give customers with a prior default credit cards rather than people without. Banks are a privately own institution design to accumulate wealth to their stockholders and in order to do that common people might be at a disadvantage. Though it is not a banks responsibility to explain their tactics. People as a collective need to start educating others on managing their own finances.Though in the USA, where the consumer mindset is heavily ingrained in us, it's easy to deter yourself from that, me included. So to promote better overall finances, we should hold each other accountable. 

So I guess my biggest takeaway with this project is that we need to educate future generations about finances and making smart decisions. Not just credit cards but 401K, Roth IRA, and investments, we have to figure out ways to finesse the system, not let the system finesse us! Because banks are a big virtue if we know how to use them correctly. Credit cards can generate cash bank and increase credit score, it's just a matter of using them responsibly.

